export const scamalertES = [
  "Se nos ha señalado que los estafadores, que pretenden actuar en nombre de EMFI Securities Limited, se han puesto en contacto con miembros del público, especialmente en Francia, utilizando fraudulentamente el nombre, la marca y otros detalles de identificación corporativa de EMFI Securities Limited. Se nos ha informado de varios casos y EMFI Securities Limited ha informado de dichos casos a las autoridades pertinentes, la Autoridad de Conducta Financiera en el Reino Unido y la Autorité des Marchés Financiers en Francia.",
  "EMFI Securities Limited presentó una denuncia penal ante el Fiscal Público de París el 5 de febrero de 2019 por falsificación y fraude de identidad. El 9 de noviembre de 2020, EMFI Securities Limited presentó otra denuncia penal ante el Tribunal Penal de París.",
  'Tenga en cuenta que EMFI Securities Limited o cualquier otra entidad del Grupo EMFI no proporciona absolutamente ningún servicio a los clientes minoristas. Todos nuestros productos y servicios están dirigidos exclusivamente a inversores calificados, clientes profesionales y contrapartes elegibles. En cualquier caso, ni EMFI Securities Limited ni ninguna otra entidad del Grupo EMFI ofrecen productos de ahorro al público en general en Francia y, en particular, no ofrecen ningún "Livret d’Epargne 6,25%".',
  "Si una parte desconocida se comunica con usted en relación con oportunidades de inversión que afirma representar a EMFI Securities Limited o cualquier otra entidad del Grupo EMFI, esté extremadamente atento. Comuníquese de inmediato con EMFI Securities Limited a través de nuestro sitio web para confirmar la legitimidad de la inversión propuesta.",
  "En cualquier caso, EMFI Securities Limited recomienda encarecidamente que consulte a sus propios profesionales fiscales, legales y contables antes de realizar cualquier transacción financiera. Por último, si cree que ha sido engañado para realizar una inversión fraudulenta, EMFI Securities Limited le sugiere encarecidamente que se ponga en contacto de inmediato con las autoridades policiales y otras autoridades reguladoras de su país.",
];
export const scamalertEN = [
  "It has been brought to our attention that fraudsters, pretending to act on behalf of EMFI Securities Limited, have been contacting members of the public, particularly in France, fraudulently using EMFI Securities Limited’s name, branding and other corporate identification details. We have been made aware of several cases and EMFI Securities Limited has reported such cases to relevant authorities, the Financial Conduct Authority in the United Kingdom and the Autorité des Marchés Financiers in France.",
  "EMFI Securities Limited filed a criminal complaint before the Paris Public Prosecutor on February 5, 2019 on the grounds of forgery and identity fraud. On November 9, 2020, EMFI Securities Limited filed another criminal complaint before the Paris Criminal Court",
  'Please note that EMFI Securities Limited or any other entity of the EMFI Group provides absolutely no services to retail clients. All our products and services are aimed solely towards qualified investors, professional clients and eligible counterparties. In any event, neither EMFI Securities Limited nor any other entity of the EMFI Group offer saving products to the general public in France and in particular do not offer any "Livret d’Epargne 6,25%".',
  "If you are contacted in relation to investment opportunities by an unknown party claiming to represent EMFI Securities Limited or any other entity of the EMFI Group, please be extremely vigilant. Please immediately contact EMFI Securities Limited through our website to confirm the legitimacy of the proposed investment.",
  "In any event, EMFI Securities Limited strongly recommends that you consult your own tax, legal and accounting professionals before engaging in any financial transactions. Finally, if you believe that you have been misled into making a fraudulent investment, EMFI Securities Limited strongly suggests that you immediately contact law enforcement and other regulatory authorities in your country.",
];
